# Generated by Django 4.0.6 on 2022-07-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qreate', '0002_webqr_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webqr',
            name='data',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
