# Generated by Django 4.0.6 on 2022-08-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qreate', '0003_alter_webqr_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webqr',
            name='data',
        ),
    ]
