# Generated by Django 4.0.6 on 2022-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qreate', '0004_remove_webqr_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webqr',
            name='name',
            field=models.URLField(),
        ),
    ]
