# Generated by Django 4.0.6 on 2022-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qreate', '0005_alter_webqr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webqr',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
