# Generated by Django 4.0.6 on 2022-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qreate', '0006_alter_webqr_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('choice_img', models.ImageField(upload_to='choice_images')),
                ('imgqr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
