# Generated by Django 4.0.6 on 2022-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qreate', '0007_imgqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmae', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='images')),
            ],
        ),
    ]
