# Generated by Django 4.0.6 on 2022-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qreate', '0008_testimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('myfile', models.FileField(upload_to='documents')),
                ('fileqr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Testimg',
        ),
    ]
